config/routes.rb
Tournoi::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :tournaments do
    member do
		get :inscriptions
		put :upstatus
	end
	resources :leagues, :controller => "phases", :type => "League", :only => [:new, :create, :update]
	resources :leagues, :only => [:show]
	resources :phases, :only => [:index, :destroy, :edit] do
		get :start, :on => :member
	end
  end
 

 
  resources :inscriptions, :only => [:create, :destroy, :update]

  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/video',   :to => 'pages#video'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

 
  root :to => "pages#home"

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def destroy
    Tournament.find(params[:id]).destroy
    flash[:success] = "Tournoi detruit."
    redirect_to tournaments_path
  end

  def index
    @title = "Tous les tournois"
    @tournaments = Tournament.all
  end

    def show
    @tournament = Tournament.find(params[:id])
	@title = @tournament.name
  end
  
  def new
    @tournament = Tournament.new
	@title = "Participez"
  end
  
  def create
    @tournament = Tournament.new(params[:tournament])
    if @tournament.save
	  flash[:success] = "Nouveau Tournoi Sauvegarde!"
      redirect_to @tournament
    else
      render 'new'
    end
  end

  def edit
	@tournament = Tournament.find(params[:id])
    @title = "Editer Tournoi"
  end
  
  def update
	@tournament = Tournament.find(params[:id])
    if @tournament.update_attributes(params[:tournament])
      flash[:success] = "Tournoi mis a jour."
      redirect_to @tournament
    else
      @title = "Editer tournoi"
      render 'edit'
    end
  end
  
    def upstatus
	@tournament = Tournament.find(params[:id])
	if @tournament.upstatus(params[:tournament][:status])
      flash[:success] = "Status du Tournoi mis a jour."
      redirect_to @tournament
    else
	  render 'show'
    end
  end
  
end

app/views/tournaments/_choix_team.html.erb
<% if current_user.titulaire?(@tournament) %>
		<%= form_for (@tournament.inscriptions.find_by_user_id(current_user)) do |f| %>
			<%= render 'shared/error_messages', :object => f.object %>
			<div class="field">
			<%= f.label :team %><br />
			<%= f.collection_select(:team_id, Teams.find(:all), :id, :name) %>
			</div>
			<div class="actions">
			<%= f.submit "Choisir Equipe" %>
			</div>
		<% end %>
<% end %>



app/views/tournaments/_desinscrit.html.erb
<%= form_for current_user.inscriptions.find_by_tournament_id(@tournament),
             :html => { :method => :delete } do |f| %>
  <div class="actions"><%= f.submit "Desinscription" %></div>
<% end %>

app/views/tournaments/_editnew.html.erb
<%= form_for(@tournament) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :game %><br />
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :support %><br />
    <%= f.text_field :support %>
  </div>
   <div class="field">
    <%= f.label :conf %><br />
    <%= f.text_field :conf %>
  </div>
  <div class="field">
    <%= f.label :participants %><br />
    <%= f.number_field :participants %>
  </div>
  <div class="actions">
    <%= f.submit button %>
  </div>
<% end %>

app/views/tournaments/_inscrit.html.erb
<%= form_for current_user.inscriptions.build(:tournament_id => @tournament.id) do |f| %>
  <div><%= f.hidden_field :tournament_id %></div>
  <div class="actions"><%= f.submit "Inscription" %></div>
<% end %>

app/views/tournaments/_inscrit_form.html.erb
<% unless current_user?(@user) %>
  <div id="inscription_form">
  <% if current_user.inscrit?(@tournament) %>
    <%= render 'desinscrit' %>
  <% else %>
    <%= render 'inscrit' %>
  <% end %>
  </div>
<% end %>

app/views/tournaments/_start.html.erb
<%= link_to "Clore Inscriptions?", 
          tournament_path(@tournament, 
                    :tournament => { :status => 2}),
          :method => :put, 
          :confirm => "Sur ?" %>

app/views/tournaments/_stop.html.erb
<%= link_to "Autoriser Inscriptions", 
          upstatus_tournament_path(@tournament, 
                    :tournament => { :status => 1}),
          :method => :put, 
          :confirm => "Sur ?" %>
		  
<%= link_to "Demarrer le tournoi", 
          upstatus_tournament_path(@tournament, 
                    :tournament => { :status => 3}),
          :method => :put, 
          :confirm => "Sur ?" %>

app/views/tournaments/_stop_start.html.erb
<% if @tournament.open? %>
    <%= render 'start' %>
  <% else %>
    <%= render 'stop' %>
<% end %>

app/views/tournaments/_tournament.html.erb
<table "class=tournament">
	<tr>
		<td class="round fixed <%= call_status_css(tournament) %>">
			<strong><%= tournament.return_status %></strong>
		</td>
		<td class="fixed">
		<strong><%= link_to tournament.name, tournament %><strong>
		</td>
		<td class="fixed">
			<% if signed_in? %> <% if current_user.inscrit?(tournament) %><%= current_user.etat_inscrit(tournament) %></strong><% end %><% end %> 
		</td>
	</tr>
</table>




		

app/views/tournaments/edit.html.erb
<h1>Editer Tournoi</h1>

<%= render :partial =>'editnew',:locals => {:button => "editer"} %>

app/views/tournaments/index.html.erb
<h1>Tous les Tournois</h1>

<strong><%= link_to "Creer Nouveau Tournoi ", new_tournament_path %></strong><br />

<ul class="tournaments">
  <%= render @tournaments %>
</ul>

app/views/tournaments/new.html.erb
<h1>Creer Tournoi</h1>

<%= render :partial =>'editnew',:locals => {:button => "Creer"} %>

app/views/tournaments/show.html.erb
<table class="tournaments">
  <tr>
	<td class="admin round">
	   <%= link_to "editer", edit_tournament_path(@tournament), :title => "Editer #{@tournament.name}" %>
	   <%= link_to "supprimer", @tournament, :method => :delete, :confirm => "Sur ?",
                                :title => "Supprimer #{@tournament.name}" %>
	    <%= render 'stop_start'%>
	</td>
  </tr>
  <%= render 'shared/error_messages', :object => @tournament %>
  <tr>
    <td class="main round">
      <h1>
        <%= @tournament.name %>
      </h1>
	  <h4><%= @tournament.return_status %></h4>
		
	  <% if signed_in? %>
		<% if @tournament.open? %>
			<%= render 'inscrit_form' %>
		<% end %>
		<% if @tournament.choix? %>
			<%= render 'choix_team' %>
		<% end %>
	  <% end %>
    </td>

    <td class="sidebar round">
      <strong>Name</strong> <%= @tournament.name %><br />
	  <strong>Description</strong> <%= @tournament.description %><br />
      <strong>URL</strong> <%= link_to tournament_path(@tournament), @tournament %><br />
      <strong>Phases</strong> <%= link_to "Voir", tournament_phases_path(@tournament)%><br />
	  <strong>Nombre</strong> <%= @tournament.phases.count %>
  
    </td>
  </tr>
  <tr>
	<td class="round">
	  <b>Participants :</b>
	    <%= @tournament.inscriptions.count %>	Sur <%= @tournament.participants %>
		<ul class="users">
			<% @tournament.users.each do |user| %>
			<li>
				<%= gravatar_for user, :size => 30 %>
				<%= link_to user.name, user %>
			</li>
			<% end %>
		</ul>
	</td>
  </tr>
</table>