config/routes.rb
Tournoi::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :tournaments do
    member do
		get :inscriptions
		put :upstatus
	end
	resources :leagues, :controller => "phases", :type => "League", :only => [:new, :create, :update]
	resources :leagues, :only => [:show]
	resources :phases, :only => [:index, :destroy, :edit] do
		get :start, :on => :member
	end
  end
 

 
  resources :inscriptions, :only => [:create, :destroy, :update]

  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/video',   :to => 'pages#video'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

 
  root :to => "pages#home"

end

app/views/phases/_editnew.html.erb
<%= form_for ([@tournament,@phase],:type => @type, :as => :phase ) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :participants %><br />
    <%= f.number_field :participants %>
  </div>
   <div class="field">
    <%= f.label :qualifies %><br />
    <%= f.number_field :qualifies %>
  </div>
  <div class="field">
  <%= f.label "Phases Parentes" %><br />
   <%= f.collection_select(:parent_phase_ids, @tournament.phases.find(:all), :id, :name, {}, :multiple => true) %>
  </div>
  <%= render :partial => @phase.type.downcase, :locals => { :f => f } %>
   <div class="actions">
    <%= f.submit button %>
  </div>
<% end %>

app/views/phases/_league.html.erb
  <div class="field">
    <%= f.label :retour %><br />
    <%= f.check_box :retour %>
  </div>
  <div class="field">
    <%= f.label :pointsvict %><br />
    <%= f.number_field :pointsvict %>
  </div>
  <div class="field">
    <%= f.label :pointsnul %><br />
    <%= f.number_field :pointsnul %>
  </div>
  

app/views/phases/_phase.html.erb
<li>
  <%= link_to "#{phase.type} #{phase.name}", polymorphic_path([@tournament,phase])%>
  <%= link_to "editer", edit_tournament_phase_path(@tournament,phase),
                                :title => "Editer #{phase.name}" %>
  <%= link_to "supprimer", tournament_phase_path(@tournament,phase), :method => :delete, :confirm => "Sur?",
                                :title => "Supprimer #{phase.name}" %>
  <%= link_to "demarrer la phase", start_tournament_phase_path(@tournament,phase), :method => :get, :confirm => "Sur?",
                                :title => "On demarre" %>
								
</li>

app/views/phases/_phase_show.html.erb
<table class="phase">
  <tr>
    <td class="main">
      <h1>
        <%= @phase.type %>
      </h1>
	    <%= @phase.name %>
    </td>

	 <%= render 'shared/error_messages', :object => @phase %>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @phase.name %><br />
	  <strong>Description</strong> <%= @phase.description %><br />
      <strong>Tournoi</strong> <%= link_to tournament_path(@tournament), @tournament %><br />
    </td>
</table>

app/views/phases/edit.html.erb
<h1>Editer Phase</h1>

<%= render :partial =>'editnew',:locals => {:button => "Mise a jour"} %>

app/views/phases/index.html.erb
<h1>Toutes les phases of <%= @tournament.name %></h1>

<strong><%= link_to "Creer Nouveau Championnat ", new_tournament_league_path(@tournament) %></strong><br />
<ul class="phases">
  <%= render :collection =>@phases, :partial => "phase" %>
</ul>

app/views/phases/new.html.erb
<h1>Creer <%= @phase.type %></h1>

<%= render :partial =>'editnew',:locals => {:button => "Creer"} %>